### ISSUE TITLE
Support for macOS 10.15

### ISSUE THREAD

**Issue by YUWEN9410** [hieplpvip/AsusSMC#20] opened 2019-06-10 05:03 UTC
The keyboard backlight failed in 10.15 beta.

**Comment by YUWEN9410** [comment] 2019-06-10 07:41
asus N552vw6700

**Comment by anonymous-writer** [comment] 2019-06-15 09:35
Also on ASUS Zenbook UX430UAK. The brightness will not changed but the icon on the laptop screen appears.
All other functions work under Catalina.

I would also like to thank you for your previous work. Until Mojave the kext works perfectly.

**Comment by hieplpvip** [comment] 2019-06-15 10:52
#### About keyboard backlight:
Have you updated VirtualSMC to latest version?
Keyboard backlight depends on SMC. That keyboard backlight doesn't work while the other functions work suggest that there's a problem with SMC simulation.

#### About screen brightness:
AsusSMC only sends fake keyboard press event (like on real Mac) to make macOS change brightness. It doesn't change brightness directly.

The fact that the badge appears means that system has successfully receive the fake keyboard event. Brightness still not working suggests that the brightness patch is not working properly.

You can try setting brightness manually in System Preferences. If it doesn't work, the problem is not with AsusSMC.

**Comment by anonymous-writer** [comment] 2019-06-15 15:32
Sorry @hieplpvip ,
I write brightness and mean keyboard backlight. Screen Brightness work perfekt.

I use VirtualSMC  1.1.1.

<img width="445" alt="Bildschirmfoto 2019-06-15 um 17 36 39" src="https://user-images.githubusercontent.com/35840715/59553376-570e5680-8f94-11e9-8943-239ee48b57cd.png">

**Comment by hieplpvip** [comment] 2019-06-15 15:49
I'd wait for final release of Catalina before updating. There's not much I can help you now, sorry.

**Comment by anonymous-writer** [comment] 2019-06-15 20:00
Small temporary solution meanwhile, this works great with Catalina and AsusSMC and keyboard backlight.

https://www.heise.de/download/product/lab-tick-37046/download

**Comment by YUWEN9410** [comment] 2019-06-16 00:27
Thanks to the author @hieplpvip  for his efforts, I have tried to use AsusNBFnKeys.kext. The keyboard backlight is normal, but the keyboard backlight icon does not appear on the computer monitor when the keyboard backlight is adjusted, because the driver is too old.

**Comment by YUWEN9410** [comment] 2019-06-16 00:44
I am now rolling back to mojave, and the keyboard backlight is normal. Maybe catalina has some bugs

**Comment by hieplpvip** [comment] 2019-06-16 00:55
@anonymous-writer What is that?

**Comment by anonymous-writer** [comment] 2019-06-16 09:23
Hello @hieplpvip ,
A keyboard backlight slider that works great with your kext and that also already works under Catalina.

<img width="445" alt="Bildschirmfoto 2019-06-16 um 11 19 02" src="https://user-images.githubusercontent.com/35840715/59562127-114f9d80-9029-11e9-9c29-eea6e2bd3cea.png">

**Comment by MohammadtaghiFarkhondekar** [comment] 2019-09-12 20:32
After installing 10.15 my keyboard doesn't working and I removed asussmc and after that keyboard start to working !
I don't know why ! Because in 10.14.6 it works very well .
What's file type do you need for debugging ?

**Comment by MohammadtaghiFarkhondekar** [comment] 2019-09-15 12:25
??? please make kext for 10.15

**Comment by hieplpvip** [comment] 2019-10-10 18:22
Hi everyone.

I've just upgraded to Catalina and had some look at the problem. It seems that macOS Catalina change how it detects if keyboard backlight is supported. On Mojave and below, simulating 2 SMC keys (`LKSB` and `LKSS`) is enough. However, that no longer works. In Keyboard section in System Preferences, we no longer see anything related to keyboard backlight (which, obviously, show that keyboard backlight is not detected).

The reason why LabTick works is that it ~~interfere directly with those 2 SMC values, and ignore the check for keyboard backlight existence~~ directly calls functions in `AppleLMUController` (renamed to `AppleSMCLMU` on Catalina), which just writes the value to `LKSB` and skips the check. For now, you guys should use it.

I'm still not sure how to fix it...

**Comment by anonymous-writer** [comment] 2019-10-11 06:26
Thank you for your feedback. I will also try to find out how the keyboard backlight are addressed at Catalina. Did I find something I write you.

**Comment by anonymous-writer** [comment] 2019-10-12 20:44
Where in the source code you can customize the output keys? To write out temporarily a different short command for use with LabTick.
<img width="437" alt="Bildschirmfoto 2019-10-12 um 22 37 56" src="https://user-images.githubusercontent.com/35840715/66707511-e0b31280-ed41-11e9-9ff7-dcfdc62a6f5b.png">

**Comment by anonymous-writer** [comment] 2019-10-12 20:55
This is also interesting and changes the keyboard brightness. Works perfect under Catalina.

https://github.com/pirate/mac-keyboard-brightness

**Comment by hieplpvip** [comment] 2019-10-13 00:22
Let me explain how each program works.

AsusSMC works by simulating SMC keys (namely LKSB, LKSS, etc. you can find them in the source code).. When macOS (Mojave and below) detects these keys, it will think that keyboard backlight is supported and show the settings for keyboard backlight. AsusSMC also simulates an Apple keyboard, so everytime a user presses Fn keys, it will send a fake event to macOS. macOS then changes the value of LKSB, which will call the update function in AsusSMC (in KeyImplementation.cpp), which will call ACPI methods to actually set the keyboard backlight value.

The methods where macOS set the value of LKSB lie in AppleLMUController.kext (which is renamed to AppleSMCLMU.kext on Catalina). Labtick/macbrightness use these method.

I believe the problem on Catalina is that it adds some more check, and I'm pretty sure it's not in AppleSMCLMU (I have tried RE it but found nothing interesting). I will RE more when I have time.

Actually, a workaround for Catalina is pretty simple. When Fn keys are pressed, we'll call ACPI methods directly, but in that way we'll lose some nice feature of macOS (auto turn off, ...), so I don't prefer it. If you guys want, I may implement it before I found a proper solution.

**Comment by gulios** [comment] 2019-10-13 08:42
IMO without auto-off is much better than LabTick ;) so if you can ;)

**Comment by hieplpvip** [comment] 2019-10-13 11:26
I'll implement it and release a new version next week.

**Comment by hieplpvip** [comment] 2019-10-13 19:54
[AsusSMC-1.2.0-RELEASE.zip](https://github.com/hieplpvip/AsusSMC/files/3722272/AsusSMC-1.2.0-RELEASE.zip)

I have added workaround for Catalina. Please test it. Don't forget to install AsusSMCDaemon. Without it you won't see the badge.

Technical explanation: Since I can't get macOS to show the badge, I have to show it manually via AsusSMCDaemon. This has two drawbacks: you have to install it and it will not work at login window (macOS doesn't load daemons there).

As I said, auto turning off and auto adjusting will not work.

**Comment by gulios** [comment] 2019-10-13 20:17
it works ;))

**Comment by anonymous-writer** [comment] 2019-10-13 20:35
Me too. You are the best.

**Comment by MohammadtaghiFarkhondekar** [comment] 2019-10-13 21:08
Is not working for me ! And after using kext my keyboard doesn't working like old v in 10.15

**Comment by hieplpvip** [comment] 2019-10-14 04:52
@MohammadtaghiFarkhondekar Are you still using Mojave? If yes, please test it on Mojave. It doesn't support HID on Catalina

**Comment by SkreamDark** [comment] 2019-10-14 06:44
Hello, thank you for new kext) now my backlight keyboard working, but not like on Mojave. In Mojave keyboardbacklight can be turn off automatically after 10 second or more. How Can i return this option?
In Mojave
![image](https://user-images.githubusercontent.com/38081153/66733074-cda25e80-ee77-11e9-9861-91accfeb4d9e.png)
In Catalina
![image](https://user-images.githubusercontent.com/38081153/66733111-e90d6980-ee77-11e9-8e3c-9f82ec74e381.png)

**Comment by gulios** [comment] 2019-10-14 07:02
> Hello, thank you for new kext) now my backlight keyboard working, but not like on Mojave. In Mojave keyboardbacklight can be turn off automatically after 10 second or more. How Can i return this option?
> In Mojave
> ![image](https://user-images.githubusercontent.com/38081153/66733074-cda25e80-ee77-11e9-9861-91accfeb4d9e.png)
> In Catalina
> ![image](https://user-images.githubusercontent.com/38081153/66733111-e90d6980-ee77-11e9-8e3c-9f82ec74e381.png)

You didn't read this issue, right ? ;)

**Comment by SkreamDark** [comment] 2019-10-14 07:25
Just very quick), but i understand, that it may be just incompatible with Catalina right now
When i saw new kext, i was so glad)
I hope its will be fixed very soon

**Comment by anonymous-writer** [comment] 2019-10-14 07:31
If you would read what is written above then all questions would be answered.

In any case, I thank the developer that he work on this kext. He finally gets nothing for this work except somtime a donation.

**Comment by MohammadtaghiFarkhondekar** [comment] 2019-10-14 19:14
I test again in 10.14.6 all off fn keys work good but keyboard back light fn key aren't working ! !!!

**Comment by hieplpvip** [comment] 2019-10-15 01:05
@MohammadtaghiFarkhondekar Test this one on Mojave
[1.2.0.RELEASE.zip](https://github.com/hieplpvip/AsusSMC/files/3726961/1.2.0.RELEASE.zip)

**Comment by MohammadtaghiFarkhondekar** [comment] 2019-10-15 13:46
No , keyboard back light FN keys aren't working again.

**Comment by hieplpvip** [comment] 2019-10-16 12:06
Could someone still having Mojave installed please send me a copy of CoreBrightness?
The location of it is `/System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness`

**Comment by SkreamDark** [comment] 2019-10-16 19:27
Here, i hope its will help you and thanks for you work) 
[CoreBrightness.framework.zip](https://github.com/hieplpvip/AsusSMC/files/3736046/CoreBrightness.framework.zip)

**Comment by hieplpvip** [comment] 2019-10-17 11:56
Does anyone have a real MacbookPro running Catalina? I need IOReg of it.

Apple really sucks. They rewrote CoreBrightness completely :(

**Comment by ghost** [comment] 2019-10-17 12:44
> Does anyone have a real MacbookPro running Catalina? I need IOReg of it.

Yep...2014 MBP

[ioreg.zip](https://github.com/hieplpvip/AsusSMC/files/3739294/ioreg.zip)

**Comment by MohammadtaghiFarkhondekar** [comment] 2019-10-18 11:29
[CoreBrightness.framework.zip](https://github.com/hieplpvip/AsusSMC/files/3743649/CoreBrightness.framework.zip)

I'm using the new Releases in 10.14.6 and 10.15 but  ,,,  asus aura back light is not working in macos 10.14.6 and in 10.15 my keyboard is not working ( any key is not working !!!)

**Comment by hieplpvip** [comment] 2019-10-18 12:42
@andrewwyatt Can you dump ioreg again, this time using [IORegistryExplorer](https://raw.githubusercontent.com/black-dragon74/OSX-Debug/master/IORegistryExplorer.zip)?

**Comment by ghost** [comment] 2019-10-18 13:23
> @andrewwyatt Can you dump ioreg again, this time using [IORegistryExplorer](https://raw.githubusercontent.com/black-dragon74/OSX-Debug/master/IORegistryExplorer.zip)?

I sent it direct, don't want to post it since I can't scrub my serials.

**Comment by SkreamDark** [comment] 2019-10-18 17:47
i have MacBook Air, will his ioreg be useful??

**Comment by ertanyanardag** [comment] 2019-10-19 00:17
Thank you, it's great work...

**Comment by DilVika** [comment] 2020-02-08 11:35
Have this problem with Keyboard backlight was fixed by the newest version, anyone? I have updated to newest ver but Keyboard backlight just not work at all.  My laptop is Gl552vx and everything worked fine on Mojave.

**Comment by Ubsefor** [comment] 2020-02-08 12:56
> Have this problem with Keyboard backlight was fixed by the newest version, anyone? I have updated to newest ver but Keyboard backlight just not work at all. My laptop is Gl552vx and everything worked fine on Mojave.

Have you updated Lilu and VirtualSMC?
For me everything works perfectly

**Comment by MohammadtaghiFarkhondekar** [comment] 2020-03-08 14:23
up..... need fixing .

**Comment by e-senturk** [comment] 2020-03-21 20:41
I am getting some progress on this issue finally i manage to work that kext in catalina but its not a solution for now. Please dont try for your daily usage it may break your system.
- I compared ioregs in catalina and mojave the key difference is a driver extension called AppleUserHIDDrivers.dext in catalina.
- In mojave there is no such driver so we can use asussmc with IOHidEventDriver but in catalina we can't use that driver because AppleUserHIDDrivers.dext interfere and connect asussmc because its a default hid behaviour on catalina. 
- I removed AppleUserHIDDrivers.dext its under System/Library/Driver Extensions. After lots of lagging and hid issues asussmc reconnected IOHidEventDriver instead of AppleUserHIDDriver and asussmc worked for a while.
- There are two way to fixing it first one is fixing incompatilibity on AppleUserHIDDrivers and AsusSmc(permenant solution), second block AppleUserHidDrivers for attached keyboard.

**Comment by williambj1** [comment] 2020-03-22 06:11
@valinor61 

Nice research!
I think we need to beat this dext from loading under the keyboard with a higher `IOProbeScore` in AsusSMC.

![image](https://user-images.githubusercontent.com/45396585/77243654-864ea400-6c47-11ea-83ae-060980cf14c5.png)


![image](https://user-images.githubusercontent.com/45396585/77243606-fb6da980-6c46-11ea-827d-d345940f6e9e.png)

**Comment by e-senturk** [comment] 2020-03-22 09:45
@williambj1 thanks,I tried IOProbeScore override on AsusSmc it did no change I didn't get any KP either. Then I write a custom info plist to override AppleUserHIDDriver actualy it did what I said but i think AsusSmc still connecting with AppleUserHIDDrivers.dext still no keyboard input. I attached test cases and my IOProbe Override info.plist kext.
[AsusSmcCatalina.kext.zip](https://github.com/hieplpvip/AsusSMC/files/4364981/AsusSmcCatalina.kext.zip)


![Catalina No Kext](https://user-images.githubusercontent.com/29388244/77246612-3b7a5f80-6c3a-11ea-95c2-7c7f51733256.png)
 Catalina - No kext installed 
![Mojave](https://user-images.githubusercontent.com/29388244/77246614-3d442300-6c3a-11ea-8861-7d8692345549.png)
 Mojave - With AsusSmc
![IOProbeScore override](https://user-images.githubusercontent.com/29388244/77246615-3ddcb980-6c3a-11ea-9b5a-c0ec6a1ec0e6.png)
 Catalina - IOProbeScore Override
![AsusSmc and Override](https://user-images.githubusercontent.com/29388244/77246616-3e755000-6c3a-11ea-905c-f5d8aff12435.png)
 Catalina - AsusSmc and IOProbeScore Override

**Closed as completed** 2020-08-17 23:13 UTC

**Comment by gulios** [comment] 2020-08-18 09:09
Cool, works on BS too;)

**Comment by Ubsefor** [comment] 2020-08-18 09:11
> Cool, works on BS too;)

Could you please post your EFI folder? I’m having troubles getting AsusSMC to work under Clover 5120 Catalina

**Comment by gulios** [comment] 2020-08-18 09:24
i don't use clover anymore

**Comment by Ubsefor** [comment] 2020-08-18 09:26
> i don't use clover anymore

Then could you please check, whether AsusSMCDaemon is loaded?
(use sudo launchctl list | grep Asus )

**Comment by rafaelmaeuer** [comment] 2020-12-27 00:03
> Cool, works on BS too;)

What does work for you in BS? Backlight in general or changing backlight brightness with fn-keys?

**Comment by gulios** [comment] 2020-12-27 16:22
> > Cool, works on BS too;)
> 
> What does work for you in BS? Backlight in general or changing backlight brightness with fn-keys?

Backlight:
- fn keys
- "turn keyboard backlight off after.." from keyboard settings
- fn+A - but it works odd so i don't use it

**Comment by gulios** [comment] 2020-12-27 16:25
> > i don't use clover anymore
> 
> Then could you please check, whether AsusSMCDaemon is loaded?
> (use sudo launchctl list | grep Asus )

yes it's loaded
```
[17:24:22] gulios :: GuliossBookHack  ➜  ~ » launchctl list | grep Asus
500	0	com.hieplpvip.AsusSMCDaemon
```

**Comment by rafaelmaeuer** [comment] 2020-12-28 11:25
> > > Cool, works on BS too;)
> > 
> > 
> > What does work for you in BS? Backlight in general or changing backlight brightness with fn-keys?
> 
> Backlight:
> 
> * fn keys
> * "turn keyboard backlight off after.." from keyboard settings
> * fn+A - but it works odd so i don't use it

strange for me its not working, linked my issue

**Comment by shiecldk** [comment] 2021-08-12 03:21
Could anyone confirm if this still works in Catalina 10.15.7 and Big Sur?

**Comment by rafaelmaeuer** [comment] 2021-08-12 21:24
Yes I can confirm its working on macOS Big Sur 11.4 with OpenCore 0.7.1, check [rafaelmaeuer/Asus-UX32VD-Hackintosh](https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh) for details.

**Comment by shiecldk** [comment] 2021-08-14 03:42
@rafaelmaeuer Could  you share your SSDT or EFI folder you use for it?
